version: "3.9"
services:
  java-mongodb:
    image: mongo:latest
    container_name: "java-mongodb"
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
  springboot-mongodb:
      build: .
      container_name: springboot-mongodb
      ports:
        - 8080:8080
      links:
        - java-mongodb
volumes:
  mongodb-data: